%% 
%% This is file `journal.cls',
%% generated with the docstrip utility.
%% 
%% The original source files were:
%% 
%% paper.dtx  (with options: `journal')
%% 
%% Copyright (C) 1993, 1996 by Wenzel Matiaske, mati1831@perform.ww.tu-berlin.de 
%% 
%% You are not allowed to distribute this file without the 
%% original source paper.dtx. For distribution of the 
%% sources see the copyright notice in the file paper.dtx. 
%% 
\def\filename{journal}
\def\fileversion{1.0i}
\def\filedate{1996/07/25}
\def\docdate{1996/07/25}
\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{journal}[\filedate\space\fileversion\space%
       LaTeX document class (wm).]
\DeclareOption*{\PassOptionsToClass{\CurrentOption}{paper}}
\ProcessOptions
\LoadClass[journal]{paper}
\endinput
%% 
%% End of file `journal.cls'.
