% emTeX mfjob file to make Malayalam fonts:
{
base=plain;
mode=hplaser[300];
output=tfm[c:\tex\fonts\@f]  pk[c:\tex\pixel\dpi@Rr\@f];
{
fonts=  mm6 mm6s mm8 mm8s
        mm10 mm10s mmsl10 mmsl10s mmb10 mmb10s
        mmc10 mmc10s mmcsl10 mmcsl10s mmcb10 mmcb10s
        mm12 mm12s mmsl12 mmsl12s mmb12 mmb12s
        mmc12 mmc12s mmcsl12 mmcsl12s mmcb12 mmcb12s
        mm17 mm17s mmc17 mmc17s mmb17 mmb17s mmcb17 mmcb17s
        mmbig mmbigo
        mmexpa12 mmexpb12 mmexpc12;
mags=s0;
}
}
